trigger:
- feature-ms-fernandoArzola-mensaje

pool:
  vmImage: ubuntu-latest

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    displayName: 'Checkout'
    steps:
    - checkout: self

- stage: Build
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
      displayName: "Build the project"

- stage: CodeReview
  jobs:
  - job: CodeReview
    displayName: 'Code Review'
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'psycatdevops'
        projectKey: 'PsyCatDevOps_microservicio-spring'
        projectName: 'microservicio-spring'
#        extraProperties: 'sonar.exclusions=src/main/java/com/example/testingweb/GretingService.java'
      displayName: "SonarCloud Prepare"
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: "$(Build.SourcesDirectory)"
        publishJUnitResults: true
        testResultsFiles: "*/TEST-.xml"
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
      displayName: "Run test"

    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'sonarqube'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'specify'
        sonarQubeGradlePluginVersion: '3.5.0.2730'
        spotBugsAnalysis: false
      displayName: "SonarQube Analysis"

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: "Deploy"
#    steps:
#    - task: Docker@2
#      inputs:
#       containerRegistry: 'Docker'
#       command: 'login'
#    - task: Docker@2
#      inputs:
#       containerRegistry: 'Docker'
#       repository: 'tu_user_docker/microservicio-spring'
#       command: 'build'
#       Dockerfile: '**/Dockerfile'
#    - task: Docker@2
#      inputs:
#       containerRegistry: 'Docker'
#       repository: 'tu_user_docker/microservicio-spring'
#       command: 'push'
#      displayName: "Deploy the container"


- stage: Test
  jobs:
  - job: Test
    displayName: "Test"
    steps:
    - script: |
        # Test commands
      displayName: "Run performance tests"