# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature-ms-fernandoArzola-mensaje

pool:
  vmImage: ubuntu-latest

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    displayName: "Checkout"
    steps:
    - checkout: self

- stage: Build
  jobs:
  - job: Build
    displayName: "Build"
    steps:
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
      displayName: "Build the project"

- stage: CodeReview
  jobs:
  - job: CodeReview
    displayName: "Code Review"
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'psycatdevops'
        scannerMode: 'Other'
      displayName: "Prepare SonarCloud analysis"
    - task: SonarCloudAnalyze@1
      displayName: "Run SonarCloud analysis"

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: "Deploy"
    steps:
    - script: |
        # Deployment commands
      displayName: "Deploy the container"

- stage: Test
  jobs:
  - job: Test
    displayName: "Test"
    steps:
    - script: |
        # Test commands
      displayName: "Run performance tests"
