trigger:
- feature-ms-fernandoArzola-mensaje

pool:
  vmImage: ubuntu-latest

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    displayName: "Checkout"
    steps:
    - checkout: self

- stage: Build
  jobs:
  - job: Build
    displayName: "Build"
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'psycatdevops'
        projectKey: 'PsyCatDevOps_microservicio-spring'
        projectName: 'microservicio-spring'
      displayName: "SonarCloud Prepare"
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'sonarqube'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'specify'
        sonarQubeGradlePluginVersion: '3.3'
        spotBugsAnalysis: false
      displayName: "Build the project"

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: "Deploy"
    steps:
    - script: |
        # Deployment commands
      displayName: "Deploy the container"
- stage: Test
  jobs:
  - job: Test
    displayName: "Test"
    steps:
    - script: |
        # Test commands
      displayName: "Run performance tests"